### ISSUE TITLE
JavaScript error (Uncaught Exception) when application tries to start

### ISSUE THREAD

**Issue by dandickout** [MasterProgs/OpenAI-Fast-GUI#1]
Trying to run on windows. Followed the instructions.

![image](https://user-images.githubusercontent.com/23708543/206252841-0ca377b7-5b06-4202-8ef8-84fcad0cb5e8.png)

Got the attached error.

What NodeJS was this developed on? I will try different versions but currently attempting to run on 16.15.0

**Comment by dandickout** [comment]
I get the same error with Node v19.2.0

**Comment by MasterProgs** [comment]
You should have a file ".env" in the same folder as the executable.

Content of the file can be : 

```
# .env file
SHORTCUT=Control+Alt+,
```


Now, it should works

**Comment by MasterProgs** [comment]
.env is now optional, default shortcut is `Ctrl + Alt + , `
